jobs: 20
cluster:
    sbatch
        --parsable
        --time {resources.time_min}
        --mem {resources.mem_mb}
        --cpus-per-task {resources.cpus}
        --output logs/slurm/slurm-%j-{rule}.out
default-resources: [cpus=2, mem_mb=512, time_min=10]
cluster-cancel: scancel
cluster-status: ./status.py